**Creating Numpy or n-d Arrays**

In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5])

In [3]:
arr1

array([1, 2, 3, 4, 5])

In [4]:
# 2 dimensional array

arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
arr5=np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
# arr6=np.arange(10)
# arr6=np.arange(5,16)
arr6=np.arange(5,16,2)
arr6

array([ 5,  7,  9, 11, 13, 15])

In [9]:
arr7=np.linspace(10,20,10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [10]:
arr8=arr7.copy()
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [11]:
#shape

In [12]:
arr1.shape

(5,)

In [13]:
arr2.shape

(2, 3)

In [14]:
arr9=np.array([[[1,2,3],[2,3,4],[6,7,8]],[[3,4,5],[5,6,7],[7,8,9]]])

In [15]:
arr9

array([[[1, 2, 3],
        [2, 3, 4],
        [6, 7, 8]],

       [[3, 4, 5],
        [5, 6, 7],
        [7, 8, 9]]])

In [16]:
 arr9.shape

(2, 3, 3)

In [17]:
arr9.ndim

3

In [18]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr2.ndim

2

In [20]:
#size

In [21]:
arr1.size

5

In [22]:
arr9.size

18

In [23]:
arr9.itemsize

8

In [24]:
arr9.dtype

dtype('int64')

In [25]:
arr8.itemsize

8

In [26]:
arr8.dtype

dtype('float64')

**NumPy Array vs Python List**

In [27]:
lista=range(100)
arr11=np.arange(100)

In [28]:
import sys

In [29]:
print(sys.getsizeof(87)*len(lista))

2800


In [30]:
print(arr11.itemsize*arr11.size)

800


In [31]:
# Speed

In [32]:
import time

In [33]:
x=range(10000000)
y=range(10000000,20000000)

start_time=time.time()

c=[(x,y) for x,y in zip(x,y)]

print(time.time()-start_time)

0.6007161140441895


In [34]:
a=np.arange(10000000)
b=np.arange(10000000,20000000)

start_time=time.time()

c=a+b

print(time.time()-start_time)

0.41654491424560547


**Indexing Slicing and Iteration**

In [35]:
arr12=np.arange(24).reshape(6,4)

In [36]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [37]:
arr12[2] #row

array([ 8,  9, 10, 11])

In [38]:
arr12[:,2] #column

array([ 2,  6, 10, 14, 18, 22])

In [39]:
arr12[:,1:3] #multiple colmns

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [40]:
arr12[3,1:3] #specific row/column

array([13, 14])

In [41]:
arr12[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [42]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [43]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [44]:
array1=np.array([1,2,3,4,5,6])
array2=np.array([4,5,6,7,8,9])

In [45]:
array1-array2

array([-3, -3, -3, -3, -3, -3])

In [46]:
array1*array2

array([ 4, 10, 18, 28, 40, 54])

In [47]:
array1*2

array([ 2,  4,  6,  8, 10, 12])

In [48]:
array2>3

array([ True,  True,  True,  True,  True,  True])

**Matrix Multiplication**

In [49]:
array3=np.arange(6).reshape(2,3)
array4=np.arange(6,12).reshape(3,2)

In [50]:
array3.dot(array4)

array([[ 28,  31],
       [100, 112]])

In [51]:
array4.max()

np.int64(11)

In [52]:
array4.min()

np.int64(6)

In [53]:
array4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [54]:
array4.max(axis=0) #column wise max

array([10, 11])

In [55]:
array4.max(axis=1) #row wise max

array([ 7,  9, 11])

In [56]:
array4.sum()

np.int64(51)

In [57]:
array4.sum(axis=0) #column ko sum

array([24, 27])

In [58]:
array4.sum(axis=1) #rows ko sum

array([13, 17, 21])

In [59]:
array4.mean()

np.float64(8.5)

In [60]:
array4.std() #Standard Deviation

np.float64(1.707825127659933)

In [61]:
np.median(array4)

np.float64(8.5)

In [62]:
np.sin(array4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [63]:
np.cos(array4)

array([[ 0.96017029,  0.75390225],
       [-0.14550003, -0.91113026],
       [-0.83907153,  0.0044257 ]])

In [64]:
np.exp(array4) #exponent

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

In [65]:
np.sqrt(array4)

array([[2.44948974, 2.64575131],
       [2.82842712, 3.        ],
       [3.16227766, 3.31662479]])

**Reshaping NP Arrays**

In [66]:
array4 #2d array

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [67]:
array4.ravel() #converts any dimension to 1d

array([ 6,  7,  8,  9, 10, 11])

In [68]:
array4.reshape(3,2) #factor huna paryo i.e. 24 xa bhane 6,4 cause 6*4 is 24

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [69]:
array4.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [70]:
array3

array([[0, 1, 2],
       [3, 4, 5]])

In [71]:
array5=np.arange(12,18).reshape(2,3)
array5

array([[12, 13, 14],
       [15, 16, 17]])

**Stacking Arrays**

In [72]:
np.hstack((array3,array5)) # horizontal stacking: Columns lai combine garne

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [73]:
np.vstack((array3,array5)) # vertical stacking: Rows lai combine garne

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

**Splitting**

In [74]:
array3

array([[0, 1, 2],
       [3, 4, 5]])

In [75]:
np.hsplit(array3,3) # Horizontal Splitting: each column ko diff array banauxa

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [76]:
np.vsplit(array3,2) # Vertical Splitting: each row ko different array banauxa

[array([[0, 1, 2]]), array([[3, 4, 5]])]

**Fancy Indexing**

In [77]:
array8 = np.arange(24).reshape(6,4)

In [78]:
array8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [79]:
array8[[0,2,4]] # row 0, 2, 4 print garna

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

**Indexing With Boolean Arrays**

In [80]:
array=np.random.randint(low=1,high=100,size=20).reshape(4,5)

In [81]:
array

array([[16, 24, 99, 43, 61],
       [78, 62, 39, 63, 47],
       [15, 45,  4, 72, 42],
       [ 9, 82, 15, 57, 12]])

In [82]:
array[0]

array([16, 24, 99, 43, 61])

In [83]:
array[0][2]

np.int64(99)

In [84]:
array>50

array([[False, False,  True, False,  True],
       [ True,  True, False,  True, False],
       [False, False, False,  True, False],
       [False,  True, False,  True, False]])

In [85]:
# Now to print items more tahn 50 you index it like this:
array[array>50]

array([99, 61, 78, 62, 63, 72, 82, 57])

In [86]:
# Multiple conditions ni launa milxa
# For example: Number greater than 50 and odd
array[(array>50) & (array%2!=0)]

array([99, 61, 63, 57])

In [87]:
#Aba yo sabb odd ra greater than 50 wala number haru lai 0 banaunu paryo re array ma then:

array[(array>50) & (array%2!=0)]=0
array

array([[16, 24,  0, 43,  0],
       [78, 62, 39,  0, 47],
       [15, 45,  4, 72, 42],
       [ 9, 82, 15,  0, 12]])