In [ ]:
# import statement
import numpy as np

In [2]:
np.random.random()

0.21777550294565295

In [3]:
np.random.seed(1) #same random value
np.random.random()

0.417022004702574

In [4]:
np.random.uniform(1,100)

72.31212485077366

In [5]:
np.random.uniform(1,100,10).reshape(2,5)

array([[ 1.01132311, 30.93092469, 15.52883319, 10.14152088, 19.43976093],
       [35.21051198, 40.27997995, 54.34285667, 42.50025693, 68.83673054]])

In [6]:
np.random.randint(1,10,15).reshape(5,3)

array([[3, 5, 8],
       [8, 2, 8],
       [1, 7, 8],
       [7, 2, 1],
       [2, 9, 9]])

**Operations**

In [7]:
a=np.random.randint(1,10,6)
a

array([4, 9, 8, 4, 7, 6])

In [8]:
np.max(a)

np.int64(9)

In [9]:
np.min(a)

np.int64(4)

In [10]:
np.argmax(a) #gives index

np.int64(1)

In [11]:
np.argmin(a)

np.int64(0)

**Problem: Replace all of the odd digits by -1**

In [12]:
a=np.random.randint(1,10,6)
a

array([2, 4, 5, 9, 2, 5])

In [13]:
a[a%2==1]=-1
a

array([ 2,  4, -1, -1,  2, -1])

In [14]:
a=np.random.randint(1,50,6)
a

array([17, 46, 42, 19, 16,  1])

In [15]:
out=np.where(a%2==1,-1,a) #not to change value in the array itself but to modify in another array
out

array([-1, 46, 42, -1, 16, -1])

In [16]:
a

array([17, 46, 42, 19, 16,  1])

**Sort**

In [17]:
a=np.random.randint(1,50,10)
a

array([ 5, 26, 48, 35, 24,  8, 27, 26, 41, 23])

In [18]:
a=np.sort(a)
a

array([ 5,  8, 23, 24, 26, 26, 27, 35, 41, 48])

In [19]:
#percentile
np.percentile(a,25)

np.float64(23.25)

In [20]:
np.percentile(a,50)

np.float64(26.0)

In [21]:
np.percentile(a,99.8)

np.float64(47.873999999999995)